Готово
htmlacademy-javascript/161585-code-and-magick-21 pull request #3
Opened 2020-09-23 17:13 UTC by Egortk

Несколько проблем:
1. Имя мага иногда выдает undefined
2. Цвет Палоьто не приминяется, хотя цвет глаз работает нормально, код и там и там идентичный

2020-09-23 20:04 UTC, blckwltz requested changes
По вопросам:

 1. Сейчас каждый из параметров иногда принимает значение `undefined`.  Это связано с тем, что функция `GET_RANDOM_VALUE` выдает значения включаю длину массива. В этом случае как раз получаем `undefined`, так как индекс последнего элемента в массиве на 1 меньше его длины

2. Связано с тем, что цвета в формате `rgb` записаны некорректно (перед скобкой не должно быть пробела)

Сейчас все еще присутствуют ошибки по `stylelint`. Если есть вопросы по настройке плагина, можем списаться или созвониться

2020-09-23 20:04 UTC, blckwltz commented on js/setup.js
> +for (var i = 0; i < 4; i++) {
По критерию [Д19](https://up.htmlacademy.ru/javascript/21/criteries#d19) в коде не должны использоваться "магические значения". 4 - как раз такое значение

2020-09-29 16:02 UTC, blckwltz requested changes
@Egortk Я не смогу принять задание, пока не будут исправлены ошибки `stylelint` во всех файлах, кроме game

2020-09-29 16:02 UTC, blckwltz commented on js/setup.js
> +for (var wizardCount = 0; wizardCount < wizardAmount; wizardCount++) {
Тут в итоге получаем 3 объекта, по заданию должно быть 4

2020-09-29 16:47 UTC, Egortk commented on js/setup.js
> +for (var wizardCount = 0; wizardCount < wizardAmount; wizardCount++) {
Тут у меня рендерит 4 объекта, не получается 3,

2020-10-01 06:55 UTC, merged